### Variables 
@api_url = http://localhost:3333

### Get All Categories
GET {{api_url}}/establishments/categories HTTP/1.1

### Create Category
POST {{api_url}}/establishments/categories HTTP/1.1
Content-Type: application/json

{
	"description": "Pizzaria"
}

### Get All Establishments
GET {{api_url}}/establishments HTTP/1.1

### Create Establishment
POST {{api_url}}/establishments HTTP/1.1
Content-Type: application/json

{
	"name": "Pizzaria do Zé",
	"about": "Melhor pizzaria da cidade",
	"address": "Rua A, nº 70",
	"whatsapp": "75 99999-9999",
	"email": "email@example.com",
	"category_id": 1
}