services:
  database:
    image: postgres:17.4
    container_name: database-pinty-delivery
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_DB=${DB_NAME:-pinty_delivery}
      - POSTGRES_USER=${DB_USERNAME:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-12345678}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-root} -d ${DB_NAME:-pinty_delivery} -h database -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: